'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ExternalLink, Home, MapPin, WalletCards } from 'lucide-react';
import { useToast } from '@/components/feedback/ToastProvider';
import { ContentColumn } from '@/components/ui/ContentColumn';

type Housing = { id: string; title: string; description: string; propertyType: string; locationLabel: string; price: string; imageUrl?: string | null; contactUrl?: string | null; createdBy?: { name?: string | null } };

export default function HousingDetail({ housingId }: { housingId: string }) {
  const { showToast } = useToast(); const [item, setItem] = useState<Housing | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let ignore = false; void fetch(`/api/housing/${housingId}`).then(async (response) => { const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || 'Moradia nao encontrada.'); if (!ignore) setItem(payload.housing); }).catch((error) => { if (!ignore) showToast(error.message, 'error'); }).finally(() => { if (!ignore) setLoading(false); }); return () => { ignore = true; }; }, [housingId, showToast]);
  if (loading) return <ContentColumn className="space-y-4 px-5 py-6"><div className="h-72 animate-pulse rounded-[28px] bg-slate-100" /></ContentColumn>;
  if (!item) return <ContentColumn className="px-5 py-10 text-center text-muted-foreground">Moradia nao encontrada.</ContentColumn>;
  return <ContentColumn className="animate-in bg-white pb-24 fade-in duration-500"><header className="relative h-72 overflow-hidden bg-foreground">{item.imageUrl ? <img src={item.imageUrl} alt={item.title} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-white/30"><Home size={72} /></div>}<div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent" /><Link href="/moradia" className="absolute left-4 top-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/90 text-foreground"><ArrowLeft size={18} /></Link><div className="absolute bottom-6 left-5 right-5 text-white"><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold uppercase tracking-widest backdrop-blur">{item.propertyType}</span><h1 className="mt-3 text-3xl font-bold">{item.title}</h1></div></header><div className="space-y-7 px-5 pt-8"><section className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-400"><MapPin size={15} /> Localizacao</p><p className="mt-2 font-bold">{item.locationLabel}</p></div><div className="rounded-3xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-400"><WalletCards size={15} /> Valor</p><p className="mt-2 font-bold">{item.price}</p></div></section><section className="border-t border-border pt-6"><h2 className="text-h3 font-bold">Sobre a moradia</h2><p className="mt-3 whitespace-pre-wrap text-body-sm leading-7 text-muted-foreground">{item.description}</p><p className="mt-4 text-xs text-slate-400">Publicado por {item.createdBy?.name || 'Membro da comunidade'}</p></section>{item.contactUrl ? <a href={item.contactUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-brand-500 px-5 py-3 text-sm font-bold text-white"><ExternalLink size={17} /> Entrar em contato</a> : null}</div></ContentColumn>;
}
