'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Briefcase, ExternalLink, MapPin, WalletCards } from 'lucide-react';
import { useToast } from '@/components/feedback/ToastProvider';
import { ContentColumn } from '@/components/ui/ContentColumn';

type Job = { id: string; title: string; company: string; description: string; employmentType: string; locationLabel: string; salary?: string | null; contactUrl?: string | null; createdBy?: { name?: string | null } };

export default function JobDetail({ jobId }: { jobId: string }) {
  const { showToast } = useToast(); const [job, setJob] = useState<Job | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let ignore = false; void fetch(`/api/jobs/${jobId}`).then(async (response) => { const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || 'Vaga nao encontrada.'); if (!ignore) setJob(payload.job); }).catch((error) => { if (!ignore) showToast(error.message, 'error'); }).finally(() => { if (!ignore) setLoading(false); }); return () => { ignore = true; }; }, [jobId, showToast]);
  if (loading) return <ContentColumn className="space-y-4 px-5 py-6"><div className="h-64 animate-pulse rounded-[28px] bg-slate-100" /></ContentColumn>;
  if (!job) return <ContentColumn className="px-5 py-10 text-center text-muted-foreground">Vaga nao encontrada.</ContentColumn>;
  return <ContentColumn className="animate-in bg-white pb-24 fade-in duration-500"><header className="relative flex min-h-72 items-end overflow-hidden bg-foreground p-6 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(45,212,191,0.28),_transparent_40%)]" /><Link href="/vagas" className="absolute left-4 top-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/15 backdrop-blur"><ArrowLeft size={18} /></Link><div className="relative"><span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold uppercase tracking-widest">{job.employmentType}</span><h1 className="mt-4 text-3xl font-bold">{job.title}</h1><p className="mt-2 flex items-center gap-2 text-white/80"><Briefcase size={16} /> {job.company}</p></div></header><div className="space-y-7 px-5 pt-8"><section className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-400"><MapPin size={15} /> Localizacao</p><p className="mt-2 font-bold text-foreground">{job.locationLabel}</p></div><div className="rounded-3xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-400"><WalletCards size={15} /> Salario</p><p className="mt-2 font-bold text-foreground">{job.salary || 'A combinar'}</p></div></section><section className="border-t border-border pt-6"><h2 className="text-h3 font-bold">Sobre a vaga</h2><p className="mt-3 whitespace-pre-wrap text-body-sm leading-7 text-muted-foreground">{job.description}</p><p className="mt-4 text-xs text-slate-400">Publicado por {job.createdBy?.name || job.company}</p></section>{job.contactUrl ? <a href={job.contactUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-brand-500 px-5 py-3 text-sm font-bold text-white"><ExternalLink size={17} /> Candidatar-se</a> : null}</div></ContentColumn>;
}
