ALTER TABLE "PostComment" ADD COLUMN "isHidden" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PostComment" ADD COLUMN "hiddenAt" TIMESTAMP(3);

ALTER TABLE "JobComment" ADD COLUMN "isHidden" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "JobComment" ADD COLUMN "hiddenAt" TIMESTAMP(3);

ALTER TABLE "HousingComment" ADD COLUMN "isHidden" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "HousingComment" ADD COLUMN "hiddenAt" TIMESTAMP(3);
